### ISSUE TITLE
Client authentication failed.

### ISSUE THREAD

**Issue by DingK-R** [NauxLiu/phphub-server#11]
URL: phphub.dev/v1/oauth/access_token

{
"message":"Client authentication failed.",
"status_code":500,
"debug":{
"line":107,
"file":"/home/vagrant/Code/phphub-server/app/OAuth/LoginTokenGrant.php",
"class":"League\OAuth2\Server\Exception\InvalidClientException"
...

表oauth_clients 中已经添加了secret，name
查看了下代码是不是缺少oauth_client_endpoints这个表？不太确定是不是。

**Comment by NauxLiu** [comment]
看下验证这块的文档

https://github.com/NauxLiu/phphub-api-doc/blob/master/access_token.md
