### ISSUE TITLE
安装完成了，访问URL地址，报错

### ISSUE THREAD

**Issue by torome** [NauxLiu/phphub-server#12]
一下是报错信息，请指教~谢谢~
Symfony \ Component \ HttpKernel \ Exception \ NotFoundHttpException

 E:\wwwroot\phphub-server\vendor\illuminate\routing\RouteCollection.php

            // inform the user agent of which HTTP verb it should use for this route.
            $others = $this->checkForAlternateVerbs($request);
     
            if (count($others) > 0) {
                return $this->getRouteForMethods($request, $others);
            }
     
            throw new NotFoundHttpException;
        }

**Comment by NauxLiu** [comment]
访问 api_routes 里面的路由需要加前缀 `v1`， 在 `.env` 里面有配置

**Comment by torome** [comment]
我在本地使用www.ph.loc，v1.ph.loc都是报一样的错误。没头绪..
API_PREFIX=v1   # API 版本
API_DEBUG=true  # 用于生产环境请关闭 DEBUG
