### ISSUE TITLE
同步数据库错误

### ISSUE THREAD

**Issue by wyrover** [NauxLiu/phphub-server#15]
[Illuminate\Database\QueryException]
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
oo long; max key length is 1000 bytes (SQL: alter table `oauth_sessions` ad
d index oauth_sessions_client_id_owner_type_owner_id_index(`client_id`, `ow
ner_type`, `owner_id`))

 [PDOException]
 SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
 oo long; max key length is 1000 bytes

**Comment by NauxLiu** [comment]
执行 `artisan migrate` 的错误？
