### ISSUE TITLE
composer 安装不过

### ISSUE THREAD

**Issue by patrick4u** [NauxLiu/phphub-server#27]
`
Generating autoload files
> php artisan clear-compiled

  [RuntimeException]
  A version is required for an API group definition.

Script php artisan clear-compiled handling the post-install-cmd event returned with an error

  [RuntimeException]
  Error Output:

`

**Comment by NauxLiu** [comment]
env 问题: https://github.com/NauxLiu/phphub-server/issues/17

**Comment by haobird** [comment]
可以先把 .env.example 改名为 .env 即可。
或者在composer.json 中修改此处为：
`"post-install-cmd": [
            "php -r \"copy('.env.example', '.env');\"",
            "php artisan key:generate",
            "php artisan clear-compiled",
            "php artisan optimize"
        ],`
