### ISSUE TITLE
听 Laravel 社区的几个领导者谈论技术的地址问题

### ISSUE THREAD

**Issue by erigo** [NauxLiu/phphub-server#8]
地址应该是：http://www.laravelpodcast.com/ 吧？

**Comment by NauxLiu** [comment]
![z kw cspknem2 vyse3spqk](https://cloud.githubusercontent.com/assets/9570112/11550150/bc60804e-99a7-11e5-80d9-ac1f6d0b3497.jpg)

**Comment by erigo** [comment]
其实我想说的是 https://github.com/NauxLiu/phphub-server/blob/master/database/migrations/2014_08_14_221225_create_tips_table.php#L42
这里的问题，原来的地址已经打不开了。：）

**Comment by NauxLiu** [comment]
:rose:  哈哈，理解错了~ 感谢
