### ISSUE TITLE
默认的route.php文件

### ISSUE THREAD

**Issue by manglestealth** [NauxLiu/phphub-server#9]
是否需要将api_routes.php中的内容复制到routes.php中？还是需要修改什么设置？

**Comment by NauxLiu** [comment]
不需要，已经在 `RouteServiceProvicder` 里面加载了。

**Comment by NauxLiu** [comment]
API 的路由访问都需要加前缀，在 `.env` 中有配置 `API_PREFIX=v1`

**Comment by manglestealth** [comment]
好的，谢谢。
